FROM node:8.2.1

ENV NODE_ENV=production
ENV HOST 0.0.0.0
ENV PORT=3000
ENV API_URL=http://www.furiganahub.com:8080
ENV API_URL_BROWSER=http://www.furiganahub.com:8080
# Expose the app port
EXPOSE 3000

RUN npm install
RUN npm run build
CMD ["npm", "start"]